import React, { useState, useEffect } from "react";
import PersonForm from "./PersonForm";
import Filter from "./Filter";
import Persons from "./Persons";
import axios from "axios";
import phoneService from "../services/phones.js";

const App = () => {
  const [persons, setPersons] = useState([]);
  const [newName, setNewName] = useState("");
  const [newNumber, setNumber] = useState("");
  const [newFilter, setFilter] = useState("");

  useEffect(() => {
    axios
      .get("http://localhost:3001/persons")
      .then((response) => setPersons(response.data));
  }, []);

  const isNotNew = () => {
    return [...persons].find((person) => person.name === newName);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!newName) return;
    if (isNotNew()) alert(`${newName} is already added to phonebook`);
    else {
      phoneService.create({ name: newName, number: newNumber });
      // getALL for to get the autoID generated by JSON SERVER.
      phoneService.getAll().then((response) => setPersons(response));
      setNewName("");
      setNumber("");
    }
  };

  const handlePerson = ({ target }) => {
    setNewName(target.value);
  };

  const handleNumber = ({ target }) => setNumber(target.value);

  const handleSearch = ({ target }) => {
    setFilter(target.value);
  };

  return (
    <div>
      <h2>Phonebook</h2>
      <Filter onChange={handleSearch} />
      <h2>Add a new</h2>
      <PersonForm
        handlePerson={handlePerson}
        handleNumber={handleNumber}
        handleSubmit={handleSubmit}
        newName={newName}
        newNumber={newNumber}
      />
      <h2>Numbers</h2>
      <Persons persons={persons} filter={newFilter} setPersons={setPersons} />
      <div>debug: {newName}</div>
    </div>
  );
};

export default App;
